---
abstract: ~
author:
  - 'Matteo Corti <matteo.corti@id.ethz.ch>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: check_diskio
no_index:
  directory:
    - inc
    - t
requires:
  Array::Unique: 0
  English: 0
  File::Slurp: 0
  List::MoreUtils: 0
  Nagios::Plugin: 0
  Nagios::Plugin::Getopt: 0
  Nagios::Plugin::Threshold: 0
  Number::Format: 0
  POSIX: 0
  Readonly: 0
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 3.2.4
