---
abstract: unknown
author:
  - 'Matteo Corti <matteo@corti.li>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: check_diskio
no_index:
  directory:
    - t
    - inc
requires:
  Array::Unique: 0
  English: 0
  File::Slurp: 0
  List::MoreUtils: 0
  Nagios::Plugin: 0
  Nagios::Plugin::Getopt: 0
  Nagios::Plugin::Threshold: 0
  Number::Format: 0
  POSIX: 0
  Readonly: 0
  perl: 5.00800
version: v3.2.6
